Mavenization, junit 4.12 is added, some refactoring.
nicolas-raoul/jakaroma pull request #11
Opened 2021-03-19 09:44 UTC by ravingbool

2021-03-19 09:53 UTC, ravingbool commented
Please create a public repo called https://github.com/nicolas-raoul/OSSRH-65862 to verify github account ownership.
It is needed due to https://issues.sonatype.org/browse/OSSRH-65862

2021-03-26 12:25 UTC, ravingbool commented
can I add some special symbols translation to KanaToRomaji.java?
aMap.put("「", "\"");
aMap.put("」", "\"");
aMap.put("。", ".");

2021-03-26 14:52 UTC, nicolas-raoul requested changes
Thanks a lot for doing that!
It compiles fine but I noticed minor problems in the script and documentation, would you mind fixing it, so that I can merge?
Cheers :-)

2021-03-26 14:52 UTC, nicolas-raoul commented on README.md
> +java jakaroma-1.0-SNAPSHOT-jar-with-dependencies.jar -jar 六本木ヒルズ森タワー
Shouldn't it be `java -jar target/jakaroma-1.0.0-SNAPSHOT-jar-with-dependencies.jar  六本木ヒルズ森タワー` instead? Notice the `target` folder and `1.0.0` version number.

2021-03-26 14:52 UTC, nicolas-raoul commented on jakaroma.sh
> +java -Dfile.encoding=UTF-8 jakaroma-1.0-SNAPSHOT-jar-with-dependencies.jar -jar $1
Same (`target` and version number)

2021-03-29 09:39 UTC, ravingbool commented on README.md
> +java jakaroma-1.0-SNAPSHOT-jar-with-dependencies.jar -jar 六本木ヒルズ森タワー
Fixed

2021-03-29 09:39 UTC, ravingbool commented on jakaroma.sh
> +java -Dfile.encoding=UTF-8 jakaroma-1.0-SNAPSHOT-jar-with-dependencies.jar -jar $1
Fixed

2021-03-29 09:40 UTC, ravingbool commented
Hello @nicolas-raoul please take a look again, I fixed the issues :)

2021-03-29 10:07 UTC, merged

2021-03-29 10:08 UTC, nicolas-raoul commented
Thanks a lot!
Please do not hesitate to fix any other issue, also the unit tests probably need some maintenance :-)

2021-03-29 10:34 UTC, ravingbool commented
Thank you for the quick response @nicolas-raoul! Have a tice day!
Max